<a href="https://colab.research.google.com/github/Genullz/sales-predictions/blob/main/Numpy_Bakery_Starter_Notebook_Corrected.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bakery Numpy Exercise (Core) 

Note: One challenge of this exercise is staying organized, so we recommend you keep track of what is going on with paper and pencil as you work through the exercise.

The selling price of 3 items at the bake sale are: \$2 for a brownie, \$1 for a cookie, \$10 for a cake.
- Assign these values to a list named price.

In [1]:
price = [2, 1, 10]
type(price)

list

The club sells 17 brownies, 40 cookies, and 1 cake.  
- Assign these values to a list named quantity_sold.

In [2]:
quantity_sold = [17, 40, 1]
type(quantity_sold)

list

In [3]:
# price * quantity

The following code will import the NumPy library.  We also use an alias (abbreviation) for most libraries. By convention, NumPy is always assigned the alias "np".  

In [4]:
import numpy as np

Since we already created lists for price and quantity, we can convert these to arrays using the following code:

In [5]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

Now, let's go back to our original problem: You would like to find the money collected for each type of item. We want the price * quantity for each item. Let's try multiplying our arrays.

In [6]:
price_array * quantity_sold_array

array([34, 40, 10])

As you saw with the above example, the multiplication was applied between the first element of each array, then between the second element of each array, and so on.  This is known as an "elementwise" calculation.  Let's look at another example of elementwise calculations.  
- First, create a NumPy array that corresponds to the cost to make each of the items sold at the bake sale.  Let's say a brownie costs \$0.25 to make, a cookie costs \$0.50 to make, and a cake costs \$5.00 to make.

In [7]:
cost_array = np.array([0.25, 0.50, 5.00])

To find the profit of each item, we want to subtract the cost from the price.  A NumPy array will perform the subtraction elementwise as shown:

In [8]:
profit_array = price_array - cost_array
print(profit_array)


[1.75 0.5  5.  ]


Suppose you wanted to identify which items made a profit greater than $2 per item.  You could use the following code to ask if the statement is true or false for each element in the array.

In [9]:
profit_array > 2.00


array([False, False,  True])

The club will also sell pies for $7 so we need to update our price_array.  Based on your experience with lists, you might think the following code would work to include an additional element to our array: 

In [10]:
price_array = price_array + [7]
print(price_array)


[ 9  8 17]


**Wait! This is not the output we wanted!**  The NumPy array did what it does best: it added seven to *each element* in the array.  To get back to the original values, we will subtract 7, then use the np.append() function to include the value 7 as desired.

In [11]:
# Just fixing the mistake
price_array = price_array - [7]
# The proper way to append an element to an array
price_array = np.append(price_array, 7)
print(price_array)


[ 2  1 10  7]


**You can also append multiple values to the array in one command.**

For example, the club want to add the following prices:  \$4.50 for fudge, \$3 for a cupcake, \$4 for a loaf of banana bread, and $9 for a torte.  Notice the use of the square brackets in the following code that appends all three values to the array at once:

In [12]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)



[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [13]:
print(price_array.dtype)


float64


It turns out nobody plans to make a torte, so they want to remove the price of that item from the array.  We will use the np.delete() command, but we need to indicate which element to delete.  We use indexing (much the same as indexing for lists) to indicate we want to remove the element at index 7 (remember to use zero-indexing) or since it is the last element, we could go from the right and use element -1. 

In [14]:
price_array = np.delete(price_array, -1)
print(price_array)


[ 2.   1.  10.   7.   4.5  3.   4. ]


Next the club decides to raise the price of cakes from \$10 to \$12.  Once again, we will need to identify the element using the index.  Cakes are at index 2.

In [15]:
price_array[2] = 12
print(price_array)


[ 2.   1.  12.   7.   4.5  3.   4. ]


1) USE THIS NOTEBOOK TO START THE CODE WHERE THE LESSON LEFT OFF.

# The Assignment Starts Here

2) Update the  quantity_sold_array to include the sale of 2 pies,  3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread.  You also realize that one of the cookies you thought was sold had actually fallen on the ground, so edit the quantity_sold_array from 40 to 39.

In [16]:
import numpy as np


In [17]:
quantity_sold = [17, 40, 1]
type(quantity_sold)

list

In [18]:
quantity_sold_array = np.array(quantity_sold)

In [19]:
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1]


In [20]:
quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
print(quantity_sold_array)

[17 39  1  2  3 16  5]


3) Determine the amount of money collected from the sale of each item at the bake sale.  

In [21]:
price = [ 2, 1,  12,   7,   4.5,  3,   4, ]
type(price)

list

In [22]:
price_array = np.array(price)
type(price_array)

numpy.ndarray

In [23]:
quantity_sold_array * price_array

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

4) Create a NumPy array "quantity_leftover" that includes the quantity of each item remaining at the end of the sale: 2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread.  Hint: Make sure to include "0" for any item that was sold out. Why is this important when creating the array?

In [24]:
quantity_leftover = [2, 1, 6, 2, 0, 0, 0]
type(quantity_leftover) 

list

In [25]:
quantity_leftover = np.array(quantity_leftover)
type(quantity_leftover)

numpy.ndarray

5) The club decides to sell the leftover items at half price and everything quickly sells out!  Determine how much money was collected from the clearance sale. 

In [26]:
clearance_price = price_array / 2
print(clearance_price)


[1.   0.5  6.   3.5  2.25 1.5  2.  ]


# Clearance price for each item 
Pie = $3.50 (1 pie left)

Tray of fudge = $2.25 (6 trays of fudge left)

Cakes = $6 (2 cakes left)

Cupcakes = $1.5 (0 left)

Loafs of Banana Bread = $2 (2 loaves of bread left)

Brownies = $1 (0 left)

Cookies = $0.50 (0 left)



In [27]:
pie_cost_array = np.array(3.50)
pie_lo_quantity_array = np.array(1)
pie_clearance_total_amount_array = pie_cost_array * pie_lo_quantity_array

In [28]:
fudge_cost_array = np.array(2.25)
fudge_lo_quantity_array = np.array(6)
fudge_clearance_total_amount_array = fudge_cost_array * fudge_lo_quantity_array

In [29]:
cakes_cost_array = np.array(6)
cakes_lo_quantity_array = np.array(2)
cakes_clearance_total_amount_array = cakes_cost_array * cakes_lo_quantity_array

In [30]:
bananabread_cost_array = np.array(2)
bananabread_lo_quantity_array = np.array(2)
bananabread_clearance_total_amount_array = bananabread_cost_array * bananabread_lo_quantity_array

In [31]:
grand_total_clearance_amount_array = np.array(fudge_clearance_total_amount_array + pie_clearance_total_amount_array + cakes_clearance_total_amount_array + bananabread_clearance_total_amount_array)
print(grand_total_clearance_amount_array)

33.0


The total amount made from the clearance sale was **$33**

6) How much total money was collected from the bake sale (including the sale of full price and clearance items)?

Hint: Your final answer should be $213.50, but you must make sure you get this answer with your NumPy coding skills!!

In [35]:
brownie_t_cost_array = np.array(2)
brownie_quantity_array = np.array(17)
brownie_total_amount_array = brownie_t_cost_array * brownie_quantity_array

cookies_t_cost_array = np.array(1)
cookies_quantity_array = np.array(39)
cookies_total_amount_array = cookies_t_cost_array * cookies_quantity_array

cupcakes_t_cost_array = np.array(3)
cupcakes_quantity_array = np.array(16)
cupcakes_total_amount_array = cupcakes_t_cost_array * cupcakes_quantity_array

pie_t_cost_array = np.array(7)
pie_quantity_array = np.array(2)
pie_clearance_total_amount_array = pie_t_cost_array * pie_quantity_array

fudge_t_cost_array = np.array(4.50)
fudge_quantity_array = np.array(3)
fudge_clearance_total_amount_array = fudge_t_cost_array * fudge_quantity_array

cakes_t_cost_array = np.array(12)
cakes_quantity_array = np.array(1)
cakes_clearance_total_amount_array = cakes_t_cost_array * cakes_quantity_array

bananabread_t_cost_array = np.array(4)
bananabread_quantity_array = np.array(5)
bananabread_clearance_total_amount_array = bananabread_t_cost_array * bananabread_quantity_array

In [36]:
price_total_amount_array = np.array(brownie_total_amount_array + cookies_total_amount_array + cupcakes_total_amount_array + pie_clearance_total_amount_array + fudge_clearance_total_amount_array + cakes_clearance_total_amount_array + bananabread_clearance_total_amount_array)
print(price_total_amount_array) 


180.5


In [37]:
overall_total_amount = np.sum(price_total_amount_array + grand_total_clearance_amount_array)
print(overall_total_amount)

213.5


The Overall total amount collected from the Bake sale was **$213.50**